### ISSUE TITLE
bot icon

### ISSUE THREAD

**Issue by sitrobotsit** [govlawtech/dva-bot-ui#15]
The bot icon is currently pulled from https://neuterbot-client-dev.azurewebsites.net/content/botImage.png. This file is a 61kb png file that has native dimensions of 720 × 720 that is then scaled down via css to 32x32. This causes the image to load slowly. I've pushed a 2kb svg version of the botImage.png in to master. Can you please upload this to the same location as the png so it can be used instead?

**Comment by nicholasamiller** [comment]
Nice, that will save some internet.  Can I just wait till I publish this whole project, or is there some reason you want the image published now?  We can just test using GitHub pages and a relative link, no?

**Comment by sitrobotsit** [comment]
Closing this, as it's no longer relevant.
