### ISSUE TITLE
Webpack hell

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#18]
```npm run build``` is failing for me with some dependency resolution errors.  First 'uglifyjs-webpack-plugin', then 'optimize-css-assets-webpack-plugin', then something else.... then I gave up and realised why web developers shouldn't sit near upper story windows.

Any ideas?

**Comment by sitrobotsit** [comment]
ah whoops. 100% my fault. Sorry about that. Looks like some of the packages I installed didn't get added to package.json for some reason. Anyway, this is fixed now. Please pull master and run `npm i` and then `npm run build` again. However, that build isn't ready to deploy just yet. So, to test, please run `npm start`. I'll get to tidying up the production build soon, but I just wanted to check you were happy using webpack. Sorry I didn't make it feel that appealing...

**Comment by nicholasamiller** [comment]
Thanks, the build script runs for me now :)
