### ISSUE TITLE
Relocate and minnify va-include.js to /shell/js directory in output build folder

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#19]
As discussed on Slack.

**Comment by sitrobotsit** [comment]
The following done in master 

1. minified and uglified builds in production and dev of va-include.js compiled to the /build/shell/ directory in production. 
2. production and dev dynamically included css variable. i.e. the chat-bot-control.css gets included locally when running `npm start` and via the neuterbot-client.azurewebsites.net domain when running `npm run build`
3. bot image is now also working in the dev build. 

`npm i` needs to be run again before this will work.
