### ISSUE TITLE
Style chat bot control

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#2]
Style chat-bot control to match host page.

**Comment by sitrobotsit** [comment]
It looks to me like someone has already done this via css on http://dvanewlegacy.prod.acquia-sites.com/ (http://dvanewlegacy.prod.acquia-sites.com/sites/all/themes/govkit/css/partials/_vcr.scss). 

Is there anything in particular that isn't looking right?

**Comment by nicholasamiller** [comment]
I intended this issue to be about styling the control itself that loads up in the iFrame. I was assuming we'd have to do a bit to make it look at least slightly consistent with the host page.  IE, mess with Telerik's stylesheet.

**Comment by nicholasamiller** [comment]
Done for now, looks great to me.
