### ISSUE TITLE
Ensure va-include script meets accessibility guidelines

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#4]
May need a title on the iFrame.

**Comment by nicholasamiller** [comment]
Requires WCAG 2.0 conformance.
Some people have said the iFrame is an issue - don't know why exactly.
Internet seems to say we just need a title on the iFrame.

**Comment by sitrobotsit** [comment]
Yes, iFrame support in screen readers can be a bit flaky but it looks to be like in this instance a screen reader would know what to do. we'd need to test this with the popular ones (Jaws and NVDA) to make sure. I'd recommend the chatbot be reviewed in the next site wide accessibility audit. As for WCAG conformance, I've added a title to the iframe as a box checking exercise, but I don't really feel this adds any meaningful value.
