### ISSUE TITLE
Bundling and minnification

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#7]
Need a build script for this.

**Comment by nicholasamiller** [comment]
There kendo.chat.js file in the js dir is allegedly all the js for the control itself in one bundle. Then I'm guessing we also need to include the DirectlineJS and markdown conversion library in the bundle.

**Comment by nicholasamiller** [comment]
As far as bundled JS goes, is it possible to bundle:
* The JS for just the chat control I uploaded in commit https://github.com/govlawtech/dva-bot-ui/commit/0af33718cb8d38706ea27923213ec5d4faab2617
* markdown-it (possibly the template for rendering adaptive cards still uses this)
* showdown
* directlineJS

That should allow us to avoid using any CDN and just have one request for all the JS dependencies, shouldn't it?

**Comment by sitrobotsit** [comment]
There was some issues compiling the minified versions of those files, so I went with Telerik's prefered method of building via npm. Hopefully the changes in structure make sense. If not, let me know and I'll write something more detailed.

**Comment by nicholasamiller** [comment]
Basically done, will deal with tweaks via separate issues.
