### ISSUE TITLE
Ensure phone numbers rendered with <tel:> tag

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#9]
The objective is that the links show as telephone links on phones, so people can click them and their phone will automatically open the dailer.

Probably the way to do this is via the same custom template that renders markdown.

**Comment by sitrobotsit** [comment]
I can see two options here;

1) the content creators extend their use of markdown to include phone numbers. e.g. "call us on 1800 550 445" is written "call us on [1800 550 445](tel:1800550445). If they do that, then the markdown rendering template will write it as a link.
2) Use JavaScript to a) find messages with phone numbers, then b) Regex replace the numbers with the markdown as per option 1 above. 

The lag on option 2 shouldn't be much. But to make sure I capture all the ways that a phone number can be written it's probably going to add 50ms+ to each response. 

Let me know what you'd like to do.

**Comment by nicholasamiller** [comment]
With option 1, how do the content creators write the telephone links?   Will it be [1800 555 445](tel:1800555445) or something like that?  Option 1 feels like the best way to go, just because it's consistent with the whole idea of the content authors doing simple formatting with Markdown.

**Comment by sitrobotsit** [comment]
Yes I agree. 
Oh, github converted the markdown I wrote haha. I've fixed that above.

**Comment by sitrobotsit** [comment]
The markdown formatting is already in place. And I've tested it creates telephone numbers as links as long as the markdown is written like this `[1800 550 445](tel:1800550445)`. Would you like me to do some regex on the already existing markdown? If so, please send me the data. Otherwise, I think this issue can be closed?
